### PR TITLE
update urls.py - RemovedInDjango110Warning

### PR DESCRIPTION
**Pull request by noamgal**
Fixing RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.

### CODE REVIEW

File: tastypie_swagger/urls.py [hunk 1]
```diff
@@ -1,13 +1,29 @@
+from django import __version__ as django_version
```
Comment (joshkehn) [inline tastypie_swagger/urls.py:1]: Probably cleaner to call [`get_version`](https://docs.djangoproject.com/en/1.9/intro/install/#verifying)

File: tastypie_swagger/urls.py [hunk 2]
```diff
@@ -1,13 +1,29 @@
...
-    url(r'^resources/$', ResourcesView.as_view(), name='resources'),
-    url(r'^schema/(?P<resource>\S+)$', SchemaView.as_view()),
-    url(r'^schema/$', SchemaView.as_view(), name='schema'),
-)
+django_version = django_version.split('.')
+main_ver = int(django_version)[0]
+secondary_ver = int(django_version)[1]
+
+if main_ver == 1 and secondary_ver < 9:
+	urlpatterns = patterns('',
```
Comment (joshkehn) [inline tastypie_swagger/urls.py:14]: Something something DRY. Declare `urlpatterns` as a list and then if the version check is earlier than 1.8 (which is when it was deprecated) wrap it in `patterns('', *urlpatterns)`

File: tastypie_swagger/urls.py [hunk 3]
```diff
@@ -1,13 +1,29 @@
...
-    url(r'^$', SwaggerView.as_view(), name='index'),
-    url(r'^resources/$', ResourcesView.as_view(), name='resources'),
-    url(r'^schema/(?P<resource>\S+)$', SchemaView.as_view()),
-    url(r'^schema/$', SchemaView.as_view(), name='schema'),
-)
+django_version = django_version.split('.')
+main_ver = int(django_version)[0]
+secondary_ver = int(django_version)[1]
+
+if main_ver == 1 and secondary_ver < 9:
```
Comment (joshkehn) [inline tastypie_swagger/urls.py:13]: Something something use `StrictVersion` instead.

``` ipython
In [1]: from distutils.version import StrictVersion

In [2]: StrictVersion("1.9")
Out[2]: StrictVersion ('1.9')

In [3]: StrictVersion("1.9") > StrictVersion("1.8")
Out[3]: True

In [4]: StrictVersion("1.9") > StrictVersion("1.10")
Out[4]: False
```

File: tastypie_swagger/urls.py [hunk 4]
```diff
@@ -1,13 +1,29 @@
+from django import __version__ as django_version
 try:
 	from django.conf.urls import patterns, include, url
 except ImportError:
 	from django.conf.urls.defaults import patterns, include, url
```
Comment (aropan) [inline tastypie_swagger/urls.py:5]: Not working in Django 1.10: first import `ImportError: cannot import name patterns`, second `ImportError: No module named defaults`.
